# Generated by Django 5.2.5 on 2026-03-17 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=255)),
                ('agent_version', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MCP Session',
                'verbose_name_plural': 'MCP Sessions',
                'db_table': 'mcp_sessions',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='MCPToolLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=128)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='mcp_server.mcpsession')),
            ],
            options={
                'verbose_name': 'MCP Tool Log',
                'verbose_name_plural': 'MCP Tool Logs',
                'db_table': 'mcp_tool_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tool_name', 'started_at'], name='mcp_tool_lo_tool_na_144144_idx'), models.Index(fields=['session', 'started_at'], name='mcp_tool_lo_session_b95926_idx')],
            },
        ),
    ]
